spring.application.name=instituteapp
server.port=8082
eureka.instance.prefer-ip-address=true 
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
message= hello from git-repo institute app refreshed
