spring.application.name=studentApp
server.port=8081
eureka.instance.prefer-ip-address=true 
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
message=hello from git-repo studentApp updated
greeting=Hello
greeting.fr=Bonjour
greeting.es=Hola
